### ISSUE TITLE
[Bug] Tables misaligns when using emoji

### ISSUE THREAD

**Issue by wakatara** [Fuco1/org-pretty-table#10]
Perhaps more of a problem with org-tables in general, but emoji characters cause the table alignment of column borders to drift off by one for every character used. 

Is there a way to fix this? I tend to use emoji quite a lot in my tables so this does mess up the alignment, sadly. 

At least with Apple Color Emoji fontset. Sample below of effect if you paste into an emacs table under org-pretty-table (I know emoji are kinda 2 character spaces but imagine the plugin could perhaps detect for this? 

```
|----+----------+----------+----------+---------+----------+-----------+-----------|
|    | Mon      | Tue      | Wed      | Thu     | Fri      | Sat       | Sun       |
|----+----------+----------+----------+---------+----------+-----------+-----------|
| Me | 💪🏼 Write | ✅ Blog  | 💪🏼 Write | ✅ Blog | ❌ Write | ✅ Astro  | ✅ Pony   |
|    | ✅ Astro | ✅ Code     | 💪🏼 Astro | ❌ Code | ❌ Astro | ✅ Coding | ✅ Code   |
|    | ❌ Game  | ✅ WO    |          | ✅ WO   |          |           | ✅ Flight |
|    |          | ❌ Movie |          |         |          |           |           |
|----+----------+----------+----------+---------+----------+-----------+-----------|
| DH |          |          |          |         |          |           |           |
|    |          |          |          |         |          |           |           |
|    |          |          |          |         |          |           |           |
|----+----------+----------+----------+---------+----------+-----------+-----------|
```

**Comment by Fuco1** [comment]
This is very difficult to solve, especially when fallback characters are used for missing glyphs and so on.  For example, my font lacks some of the box drawing characters and so the entire thing misalignes and looks horrible.

The emoji characters could be 2 characters wide, but could also be 1.94 characters wide.  Things can be whitespace-aligned with a pixel accuracy (as demonstrated for example here https://github.com/Fuco1/justify-kp), but the glyphs can't be stretched, so if it doesn't align, the dashes wont fit.

**Comment by wakatara** [comment]
Could the emoji characters default to 2 characters wide and then simply pad
the difference?
(I have to admit I am no expert on font issues, but curious as to how this
might possibly be worked around nicely. =] ).

thanks for replying!

**Comment by Fuco1** [comment]
I would say it's too complicated.  Because this is also the interplay between the box drawing characters and regular characters and emoji, and all of them can have different widths, and in case of missing glyphs entirely different fonts might be used.

It sure is possible, but I don't think I have the capacity to spend time fixing this.

**Comment by Fuco1** [comment]
For me it looks like this.  It seems this is a property of the font you are using.  I'm using JetBrains Mono.

![image](https://user-images.githubusercontent.com/2664959/222982057-24156fcf-d530-485f-9f05-5d799fe75efa.png)

**Comment by Fuco1** [comment]
I'll close this because it's out of scope of this package to fix font issues :/ sorry.
