### ISSUE TITLE
A few comments

### ISSUE THREAD

**Issue by tecosaur** [Fuco1/org-pretty-table#2]
This may be abandoned, but I've just found it, and I like it ... a lot.

Two deficiencies I have come across:
 - It changes hyphens `-` for the entire buffer, not just tables
 - `+` symbols remain unchanged, perhaps `┼` could be handy?

I see you weren't that interested in upstreaming it five years ago, but it would now fit in very nicely with org pretty entities.

Is there any chance you may work on this some more in the future?

**Comment by Fuco1** [comment]
The code for the `+` is already there, probably just doesn't work anymore :D Although I don't think org table syntax changed at all.  Weird.

```elisp
         ((equal "+" match)
          (cond
           ((and (eq (following-char) ?-)
                 (save-excursion
                   (backward-char 1)
                   (eq (preceding-char) ?-))
                 (save-excursion
                   (backward-char 1)
                   (previous-line)
                   (eq (following-char) ?|))
                 (save-excursion
                   (backward-char 1)
                   (next-line)
                   (eq (following-char) ?|)))
            (put-text-property (match-beginning 0) (match-end 0) 'display "┼")
            t)
```

The hyphen fix should be quite simple, we need to find the table, then get its limits (`org-table-begin` and `org-table-end`) and then use `narrow-to-region` to limit the scope of replacement.

I don't think I'll work on this in the future, I think I did it basically as a demo for someone who was interested in text properties and stuff.

But who knows, I'm doing a lot of presentations with https://github.com/takaxp/org-tree-slide lately so pretty tables might come handy some day.  But no promises.

**Comment by tecosaur** [comment]
Thanks for getting back to me, and outlining the fix :)
I'll be overjoyed if I see this in the future.
Unfortunately, I'm lisp-illiterate — so I'll just hope for now.

**Comment by Yevgnen** [comment]
The `+` does not work with `GNU Emacs 27.1 (build 1, x86_64-apple-darwin20.1.0, Carbon Version 164 AppKit 2022.1) of 2020-11-15` and org 9.4/9.5-dev.

<img width="323" alt="Screen Shot 2020-11-24 at 8 40 04 AM" src="https://user-images.githubusercontent.com/16749790/100031467-aebf1b80-2e30-11eb-8022-06749962b9b7.png">

**Comment by daemianmack** [comment]
I'm intermittently experiencing the same issue with the `+` character. 

For what it's worth, disabling the mode and re-enabling `org-pretty-table` mode seems to fix the issue.

(GNU Emacs 28.0.50, stock org-mode.)

**Comment by Fuco1** [comment]
I've pushed some code to fix the + and other issues.  If this resurfaces please let me know :pray:

**Comment by Fuco1** [comment]
> It changes hyphens - for the entire buffer, not just tables

I also fixed this
