### ISSUE TITLE
[Tutorial] How to install this package

### ISSUE THREAD

**Issue by Cor73** [Fuco1/org-pretty-table#5]
Hi,

This is an excellent package, however there are no instructions for how to install it.
If you are new to emacs and don't understand how to install this, here are some directions:

1. Download the **org-pretty-table.el** file into some folder in your hard drive (I created a folder called **emacs_plugins** on my Desktop and put it in there)
2. Put the following code into your .emacs file:

```
(add-to-list 'load-path "/Users/cor/Desktop/emacs_plugins/")
(require 'org-pretty-table)
(add-hook 'org-mode-hook (lambda () (org-pretty-table-mode)))
```
3. Now restart emacs and you should be done!

Of course, you can substitute **/Users/cor/Desktop/emacs_plugins/** with whatever directory you put the **org-pretty-table.el** file into.

**Comment by Fuco1** [comment]
Hi.  I adapted your instructions and put them to the readme.  Thanks for the contribution!
