### ISSUE TITLE
indentation

### ISSUE THREAD

**Issue by vzaliva** [Fuco1/org-pretty-table#7]
Indented tables not rendered properly. Consider this example:

```

This works:

|---+---|
| A | B |
|---+---|
| 1 | 2 |
| 3 | 4 |
|---+---|

This Does not:

 |---+---|
 | A | B |
 |---+---|
 | 1 | 2 |
 | 3 | 4 |
 |---+---|
```
(note that 2nd table is indented by 1 space).
The rendering:

![image](https://user-images.githubusercontent.com/86581/138506067-5f400934-7407-4a2d-b57e-2565c5f060c4.png)

**Comment by Fuco1** [comment]
Thanks for the report, should be fixed in the latest commit.

**Comment by vzaliva** [comment]
thanks!
